### PR TITLE
Get tags DB 

### PR DESCRIPTION
**Pull request by Danwhy**
ref #359
Reduces number of requests to the database for getting tags. Should hopefully speed up page load times

### CODE REVIEW

**Review by nelsonic — APPROVED** [review]
@Danwhy 🎉

**Comment by shouston3** [comment]
Looks good 👍

**Review by samhstn — APPROVED** [review]
Looks good 👍

**Review by SimonLab — APPROVED** [review]
LGTM

**Comment by SimonLab** [comment]
@Danwhy just a merge conflict to resolve otherwise it looks good :+1:

**Pull request merged**
