### PR TITLE
Get content refactor

### PR DESCRIPTION
**Pull request by samhstn**
Will need to rebase after #297 is merged

See #287

### CODE REVIEW

**Comment by shouston3** [comment]
Put on hold until this has been answered:

https://stackoverflow.com/questions/44390950/dynamically-selecting-map-ecto

**Comment by shouston3** [comment]
Answered

**Review by nelsonic — APPROVED** [review]
@shouston3 looks good. 👍

**Review by Danwhy — APPROVED** [review]

**Review by SimonLab — APPROVED** [review]
:+1:

**Pull request merged**
