### PR TITLE
Migrate from (Phoenix): Django

### PR DESCRIPTION
**Pull request by samhstn**
Ref #483

### CODE REVIEW

**Comment by shouston3** [comment]
No longer working from this repo

**Comment by nelsonic** [comment]
@shouston3 if you want to preserve history you _can_ git _sub-module_ this repo (`/app`) 
into `/cms` and the _pick_ out the files you want to keep (`git mv my-client-file.js ../static/js` etc.)

**Comment by shouston3** [comment]
@nelsonic 👍  Nice we'll do this for our `css` and `js` files

**Comment by nelsonic** [comment]
yeah, the _advantage_ is that it preserves commit messages (_which are linked to issues, which makes tracing the reason for a feature easier when there is a "bug" to be investigated..._) 😉

**Pull request closed without merging**
