### PR TITLE
Likes functionality

### LINKED ISSUE #175: Fix dump data
The current dump data is broken
We are going to work from dump data on the app
Ensure dump data can pass all the tests

### PR DESCRIPTION
**Pull request by samhstn**
See #70 

Using this branch over #172 
Fixes #175

### CODE REVIEW

**Comment by nelsonic** [comment]
@shouston3 tests still not "_fixed_". please re-assign when passing. thanks. 👍

**Comment by shouston3** [comment]
@nelsonic 
- [x] Credo issues addressed
- [x] Increased coverage from 77% -> 96%
- [x] Further coverage improvements will be addressed from #176

**Review by nelsonic — COMMENTED** [review]
@shouston3 code looks good. thanks for improving coverage. please prioritise getting back up to 100% for the start of the next sprint. https://github.com/LDMW/app/issues/176
Keep up the great work! 🚀

**Review by SimonLab — APPROVED** [review]
Code is good :+1:

**Pull request merged**
