### PR TITLE
Sass

### PR DESCRIPTION
**Pull request by shouston3**
See #205

+ Initial modularising of the `app.css` file into sass files
+ Redoing the `package-lock.json` file to get rid of install errors

This pr is more to get the initial structure for sass modularisation in rather than a complete refactor

### CODE REVIEW

**Comment by iteles** [comment]
@shouston3 From the issue it looks like this was never agreed upon.
I would like to see more detail on why this is a good idea and approval from the technical architect (@nelsonic) on adding more technologies to the stack before it happens please.

**Comment by shouston3** [comment]
@iteles Sorry, I should have clarified this better in the issue

I've updated the issue with my comments as to why we should do this

**Comment by nelsonic** [comment]
> https://github.com/LDMW/app/issues/205#issuecomment-311086006

**Comment by shouston3** [comment]
See https://github.com/LDMW/app/issues/205#issuecomment-311086006

**Pull request closed without merging**
