### PR TITLE
setting up tests for our static endpoints

### PR DESCRIPTION
**Pull request by samhstn**
See #218

### CODE REVIEW

**Review by nelsonic — APPROVED** [review]
@shouston3 looks good. 🎉

**Review by Danwhy — APPROVED** [review]

**Review by SimonLab — APPROVED** [review]
LGTM, just a small merge conflict to resolve otherwise good to merge :+1:

**Comment by shouston3** [comment]
@nelsonic As @SimonLab is not going to be QA for the next couple of days could you look at merging these in if they're still good to go

**Comment by nelsonic** [comment]
Thanks @shouston3. merging. 👍

**Pull request merged**
