### PR TITLE
Feedback

### PR DESCRIPTION
**Pull request by samhstn**
See #203

### CODE REVIEW

**Review by nelsonic — COMMENTED** [review]
@shouston3 the work you have done on this branch is _good_...
but my _preference_ would be to use/extend the work done in https://github.com/dwyl/feedback 
and run it as an "Umbrella App". 🤔 
That way we have _re-useable_ code.
Whereas the `default` is _still_ to lock up good work in projects instead of in re-useable components ... 😞

**Comment by shouston3** [comment]
This ldmw feedback pr is coupled to wagtail (so we have less control with how the feedback form will be laid out) and sends the feedback to a google sheet.
The dwyl feedback repo sends feedback via emails.

I can't see the areas which I can reuse code.

@nelsonic Let me know which pieces could be reused

**Comment by nelsonic** [comment]
@shouston3 dwyl/feedback saves feedback to a Database. 
Wagtail uses a database.
We could push the data to Google Spreadsheets (_even though this is **terrible** place to store feedback data!_)
***Or*** we can _display_ the data using http://www.metabase.com which is a _much_ better way to display data.
Now, as for not "seeing" how to re-use code ... why _ask_ someone e.g: @jackcarlisle how to re-use the feedback app. And, `if` it's _not_ re-useable then open an issue describing the _exact_ problem you are facing in re-using it. because our job is not to `continue` building one-off apps that have _zero_ re-usability. 
escalator

**Review by SimonLab — APPROVED** [review]
@shouston3 the code looks good :+1: 
I haven't yet look at the feedback app code to know which part can be reuse or adapt for this application, so I let you decide on how to do it. Agree with @nelsonic that it would be nice to see how to reuse more components.

**Comment by shouston3** [comment]
@SimonLab As this pr as 4 pr depending on it.

Reusing components from dwyl/feedback won't be done in this pr, but could be done in a later one

**Comment by SimonLab** [comment]
@shouston3 :+1: it might be worth to create a new issue for reusing feedback component if it doesn't exists yet

**Comment by nelsonic** [comment]
@shouston3 under _no_ circumstances can we use "_4 pr depending on it_" as an _excuse_ to rush this PR. There are _very_ few companies that will guaranteed work on Open Source for people. One of the _conditions_ is that code is written in such a way that it is _re-useable_. _Currently_ the code in LDMW is **100%** Bespoke which has _several major_ downsides.

@SimonLab I _respect_ that it was _your_ decision to merge this PR. 
I'm not "_offended_" that my comment(s) were (_totally_) ignored.

I will do a _much_ better job of making it _crystal_ clear to _everyone_ in the future that our _primary_ objective as "_developers_" is to make the job(s) of our future selves/teammates as easy as possible by building/using re-useable components wherever possible. 👍

**Comment by shouston3** [comment]
(Sent yesterday in private chat - posting here for discussion)

I’m all for making reusable components when there is the opportunity for it, but I still can’t see a good way to do it between dwyl/feedback and our app. And neither can Dan or Jack.
I might have misinterpreted the abstraction you had in mind.
Was the abstraction a form submission (or multiple form submissions) to postgres?
If that is the abstraction, I feel that even if we were rendering our forms with phoenix templating in both applications, Phoenix already does enough abstraction for us that there is no more room for further abstraction.
Can you reference an example where form submission abstraction has been done into a reusable component with Phoenix or explain the abstraction you had in mind clearer

**Pull request merged**
