### PR TITLE
Pros cons

### PR DESCRIPTION
**Pull request by katbow**
#452 

* Create a button on each resource to view/hide 'pros and cons' on mobile view
* Do not display button on mobile if there are no pros or cons for that resource
* Hide 'pros and cons' content on mobile view unless toggled by button
* Display 'pros and cons' on desktop
* Display pros in one section and cons in another (side by side on desktop)
* Divide pros and cons with a line on desktop
* Display pros in one section stacked above cons in another (on mobile)

Note for reviewing: You will need to move some content from body to the pros/cons sections

### CODE REVIEW

**Comment by Cleop** [comment]
image
This button is grey for me. Is it because we had to remove the color of the secondary btn background to be transparent for the BETA banner, is it defaulting to grey for this?

**Comment by Cleop** [comment]
Maybe add a touch more padding above the pros/cons button:
**Actual:**

**Designs:**

**Comment by katbow** [comment]
sure thing, and just realised I need to bold the 'Would you recommend this?' as well.

**Comment by katbow** [comment]
|> This button is grey for me. Is it because we had to remove the color of the secondary btn background to be transparent for the BETA banner, is it defaulting to grey for this?

Hmm I'll look at this. We previously had a light & dark style for secondary buttons, however I think there is only the "light" in use now. Perhaps the dark can be converted to transparent instead.

**Review by Cleop — CHANGES_REQUESTED** [review]
Looks great. Just those 2 small things and then we should be good to go 👍

**Review by Cleop — APPROVED** [review]

**Comment by Cleop** [comment]
Great, thanks @katbow nice stuff!

**Pull request merged**
