### PR TITLE
Quicklinks

### PR DESCRIPTION
**Pull request by samhstn**
## Merge with https://github.com/LDMW/cms/pull/47

- [x] Setup wagtail panel for quicklinks
- [x] Render quicklinks
- [x] When a quicklink is clicked we send the same request as if we searching for that link value

### CODE REVIEW

**Comment by shouston3** [comment]
@Danwhy I'm having a little trouble with this atm, I can't seem to send through the querystring in the `params`

I am never able to get pattern match for `{"query" => {""query_string" => query_string}}`

[here's my attempt](https://github.com/LDMW/app/pull/403/files#diff-150bd2c9aca5d319bbe5c6ca7b6fb8f6R49)

**Comment by Danwhy** [comment]
You need to take the current query string from the url:
```<%= hidden_input f, :query_string, value: @conn.query_string %>```

**Comment by shouston3** [comment]
Doing so doesn't seem to put `query_string` into the `params`. That code sends a request with `%{"quicklink1" => nil, "q" => ""}`

When I thought it should send: `%{"query_string" => "quicklink1" => nil, "q" => ""}` or something

**Review by nelsonic — APPROVED** [review]
@shouston3 code looks good. 👍

**Review by SimonLab — APPROVED** [review]
:+1: LGTM

**Pull request merged**
