### PR TITLE
Remove duplicate categories

### PR DESCRIPTION
**Pull request by Cleop**
Relates #193 

- Revises data structure using maps and tuples in order to generate categories only once
- Refactored
- Fully tested/ documented

### CODE REVIEW

**Comment by Cleop** [comment]
Just checking out why the build is failing....

**Comment by nelsonic** [comment]
Hi @Cleop I've been _assigned_ to this PR but it still has "WIP" in the title:
image
Do you consider it "_ready for review_" or still "work-in-progress"?
***Or*** are you requesting _feedback_ to confirm work is in the "right direction"?
Thanks!

**Comment by Cleop** [comment]
My mistake, forgot to remove it. Thanks for spotting @nelsonic, now removed.

**Review by nelsonic — APPROVED** [review]
@Cleop LGTM! 🎉

**Review by samhstn — APPROVED** [review]
LGTM @Cleop 👍

**Review by Danwhy — APPROVED** [review]
:+1:

**Review by SimonLab — APPROVED** [review]
:+1: LGTM

**Pull request merged**
