### PR TITLE
Reverting password protection

### PR DESCRIPTION
**Pull request by samhstn**
Undoing everything from #81

See [comment](https://github.com/LDMW/app/issues/39#issuecomment-300750802) for why

### CODE REVIEW

**Review by nelsonic — APPROVED** [review]
@shouston3 👍 
(_but a bit more explanation as to **Why** in the PR description is **always** a good idea..._)

**Comment by shouston3** [comment]
@nelsonic Add reference to why 👍

**Review by Danwhy — APPROVED** [review]
😢 👍

**Comment by SimonLab** [comment]
Would it be easier to just remove the authentication plug from the page and to keep the password logic just in case it will be reuse later on? But this means that we have some unused code.

**Comment by shouston3** [comment]
@SimonLab We could have done, but that hasn't been mentioned as being functionality in the near future and I prefer not having unused code in the codebase and it wasn't too much hasstle

**Review by SimonLab — APPROVED** [review]
:+1:

**Comment by SimonLab** [comment]
I think we could also update/delete the password section of the Redame?

**Pull request merged**
